name: CI/CD Tienda - Backend
on:
  push:
    paths: [ "backend/**" ] # Se activa solo al tocar backend
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push image
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL_BACKEND }}:latest ./backend
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} --document-name "AWS-RunShellScript" --parameters 'commands=["aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}", "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest", "docker stop tienda-backend || true", "docker rm tienda-backend || true", "docker run -d --name tienda-backend -p 3001:3001 ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"]'